package dev.rbd;
import dev.rbd.rules.*;
import dev.rbd.rules.WorldRules.Setting;
import java.util.List;
/** World-local rules in Minecraft's Create/Edit World game-rule screen. */
public final class RbdConfig {
    public static final net.neoforged.neoforge.common.ModConfigSpec SPEC=LegacyConfig.SPEC;
    public static final Setting<Boolean> AUTO_BIND=WorldRules.bool("rbdAutoBindSingleplayer",()->LegacyConfig.SPEC.isLoaded()?LegacyConfig.AUTO_BIND.get():LegacyConfig.AUTO_BIND.getDefault());
    public static final Setting<Integer> MAX_HOLDERS=WorldRules.integer("rbdMaxHolders",()->LegacyConfig.SPEC.isLoaded()?LegacyConfig.MAX_HOLDERS.get():LegacyConfig.MAX_HOLDERS.getDefault(),0,2147483647);
    public static final Setting<Boolean> AUTO_BIND_JOIN=WorldRules.bool("rbdAutoBindOnJoin",()->LegacyConfig.SPEC.isLoaded()?LegacyConfig.AUTO_BIND_JOIN.get():LegacyConfig.AUTO_BIND_JOIN.getDefault());
    public static final Setting<Boolean> RECORD_CREATURES=WorldRules.bool("rbdRecordUnnamedCreatures",()->LegacyConfig.SPEC.isLoaded()?LegacyConfig.RECORD_CREATURES.get():LegacyConfig.RECORD_CREATURES.getDefault());
    public static final Setting<Integer> CLIENT_WIDTH=WorldRules.integer("rbdClientMemoryWidth",()->LegacyConfig.SPEC.isLoaded()?LegacyConfig.CLIENT_WIDTH.get():LegacyConfig.CLIENT_WIDTH.getDefault(),0,3840);
    public static final Setting<Integer> RASTER_WIDTH=WorldRules.integer("rbdMemoryRasterWidth",()->LegacyConfig.SPEC.isLoaded()?LegacyConfig.RASTER_WIDTH.get():LegacyConfig.RASTER_WIDTH.getDefault(),16,1920);
    public static final Setting<Integer> RASTER_HEIGHT=WorldRules.integer("rbdMemoryRasterHeight",()->LegacyConfig.SPEC.isLoaded()?LegacyConfig.RASTER_HEIGHT.get():LegacyConfig.RASTER_HEIGHT.getDefault(),9,1080);
    public static final Setting<Integer> VISUAL_INTERVAL=WorldRules.integer("rbdMemoryImageIntervalTicks",()->LegacyConfig.SPEC.isLoaded()?LegacyConfig.VISUAL_INTERVAL.get():LegacyConfig.VISUAL_INTERVAL.getDefault(),1,1200);
    public static final Setting<Integer> PERCEPTION_DISTANCE=WorldRules.integer("rbdPerceptionDistance",()->LegacyConfig.SPEC.isLoaded()?LegacyConfig.PERCEPTION_DISTANCE.get():LegacyConfig.PERCEPTION_DISTANCE.getDefault(),4,256);
    public static final Setting<Double> MIASMA_RANGE=WorldRules.decimal("rbdMiasmaSensingRange",()->LegacyConfig.SPEC.isLoaded()?LegacyConfig.MIASMA_RANGE.get():LegacyConfig.MIASMA_RANGE.getDefault(),1,256);
    public static final Setting<Double> DEATH_DWELL=WorldRules.decimal("rbdMemoryDeathDwellSeconds",()->LegacyConfig.SPEC.isLoaded()?LegacyConfig.DEATH_DWELL.get():LegacyConfig.DEATH_DWELL.getDefault(),0,30);
    public static final Setting<List<? extends String>> MILESTONES=WorldRules.list("rbdCheckpointAdvancements",()->LegacyConfig.SPEC.isLoaded()?LegacyConfig.MILESTONES.get():LegacyConfig.MILESTONES.getDefault());
    public static final Setting<Boolean> RECORD_PLAYERS=WorldRules.bool("rbdRecordPlayers",()->true);
    public static final Setting<Boolean> RECORD_VILLAGERS=WorldRules.bool("rbdRecordVillagers",()->true);
    public static final Setting<Boolean> RECORD_NAMED=WorldRules.bool("rbdRecordNamedCharacters",()->true);
    public static final Setting<Boolean> RECORD_CHAT=WorldRules.bool("rbdRecordChat",()->true);
    public static final Setting<Boolean> RECORD_SOUNDS=WorldRules.bool("rbdRecordSounds",()->true);
    public static final Setting<Boolean> RECORD_INTERACTIONS=WorldRules.bool("rbdRecordInteractions",()->true);
    public static final Setting<Boolean> RECORD_BLOCK_ACTIONS=WorldRules.bool("rbdRecordBlockActions",()->true);
    public static final Setting<Boolean> AUTO_NAME_VILLAGERS=WorldRules.bool("rbdAutoNameVillagers",()->true);
    public static final Setting<Double> CONTACT_RANGE=WorldRules.decimal("rbdRecognitionRange",()->16.0,0,256);
    public static final Setting<Double> CONTACT_DOT=WorldRules.decimal("rbdRecognitionLookDot",()->0.65,-1,1);
    public static final Setting<Double> RASTER_FOV=WorldRules.decimal("rbdPerceptionFovScale",()->0.70,0.01,10);
    public static final Setting<Double> SOUND_RANGE=WorldRules.decimal("rbdHearingRange",()->16.0,0.01,256);
    public static final Setting<Integer> MIASMA_INTERVAL=WorldRules.integer("rbdMiasmaIntervalTicks",()->20,1,2147483647);
    public static final Setting<Double> DEATH_MIASMA=WorldRules.decimal("rbdDeathMiasmaGain",()->1.0,0,1000000);
    public static final Setting<Double> TABOO_MIASMA=WorldRules.decimal("rbdTabooMiasmaGain",()->1.0,0,1000000);
    public static final Setting<Boolean> TABOO_ENABLED=WorldRules.bool("rbdDisclosureTaboo",()->true);
    public static final Setting<Integer> TABOO_TICKS=WorldRules.integer("rbdTabooEffectTicks",()->60,0,2147483647);
    public static final Setting<Integer> TABOO_SLOWNESS=WorldRules.integer("rbdTabooSlownessAmplifier",()->5,0,255);
    public static final Setting<Boolean> LIBRARY_GENERATE=WorldRules.bool("rbdGenerateArchive",()->true);
    public static final Setting<Integer> LIBRARY_X=WorldRules.integer("rbdArchiveOffsetX",()->48,-29999000,29999000);
    public static final Setting<Integer> LIBRARY_Z=WorldRules.integer("rbdArchiveOffsetZ",()->48,-29999000,29999000);
    public static final Setting<Double> LIBRARY_REACH=WorldRules.decimal("rbdShelfReach",()->8.0,0,256);
    public static final Setting<Boolean> REQUIRE_KNOWN=WorldRules.bool("rbdRequireRecognition",()->true);
    public static final Setting<Boolean> SELF_READING=WorldRules.bool("rbdAllowSelfReading",()->true);
    public static final Setting<Boolean> READ_LOCK=WorldRules.bool("rbdLockBodyWhileReading",()->true);
    public static final Setting<Integer> SEGMENT_FRAMES=WorldRules.integer("rbdMemorySegmentFrames",()->200,1,2147483647);
    public static final Setting<Integer> SOUL_SAVE_TICKS=WorldRules.integer("rbdSoulSaveIntervalTicks",()->100,1,2147483647);
    public static final Setting<Boolean> AUTO_CHECKPOINT=WorldRules.bool("rbdAutoCheckpoint",()->true);
    public static final Setting<Integer> AUTO_CHECKPOINT_INTERVAL=WorldRules.integer("rbdAutoCheckpointIntervalTicks",()->12000,20,2147483647);
    public static final Setting<Integer> AUTO_CHECKPOINT_QUIET=WorldRules.integer("rbdAutoCheckpointSafeTicks",()->200,0,2147483647);
    public static final Setting<Double> AUTO_CHECKPOINT_HEALTH=WorldRules.decimal("rbdAutoCheckpointMinHealthPercent",()->75.0,0,100);
    public static final Setting<Integer> MEMORY_QUEUE_MIB=WorldRules.integer("rbdMemoryWriteQueueMiB",()->64,1,4096);
    public static final Setting<Integer> IMAGE_QUEUE_MIB=WorldRules.integer("rbdClientImageQueueMiB",()->64,1,4096);
    public static final Setting<Boolean> REUSE_SNAPSHOT_FILES=WorldRules.bool("rbdReuseSnapshotFiles",()->true);
    public static final Setting<Integer> CHECKPOINT_RETENTION=WorldRules.integer("rbdCheckpointRetention",()->1,1,2147483647);
    public static final Setting<Integer> FAILED_WORLD_RETENTION=WorldRules.integer("rbdFailedWorldRetention",()->1,0,2147483647);
    public static final Setting<Double> RETURN_DWELL=WorldRules.decimal("rbdReturnEndingSeconds",()->4.0,0,86400);
    public static final Setting<Double> ECHO_SECONDS=WorldRules.decimal("rbdReturnEchoSeconds",()->5.0,0,86400);
    public static final Setting<Double> ECHO_COOLDOWN=WorldRules.decimal("rbdDeathSiteRecallDelaySeconds",()->10.0,0,86400);
    public static final Setting<Double> ECHO_RANGE=WorldRules.decimal("rbdDeathSiteRecallRange",()->5.0,0,256);
    public static final Setting<Double> READ_FADE=WorldRules.decimal("rbdReadingFadeSeconds",()->0.6,0,86400);
    public static final Setting<Double> READ_TITLE=WorldRules.decimal("rbdReadingTitleSeconds",()->3.0,0,86400);
    public static final Setting<Integer> CAPTION_TICKS=WorldRules.integer("rbdMemoryCaptionTicks",()->100,0,2147483647);
    public static final Setting<Boolean> REDUCED_EFFECTS=WorldRules.bool("rbdReducedEffects",()->false);
    public static final Setting<Boolean> RETURN_ECHOES=WorldRules.bool("rbdReturnEchoes",()->true);
    public static final Setting<Double> VISUAL_INTENSITY=WorldRules.decimal("rbdVisualIntensity",()->0.8,0,1);
    public static final Setting<Double> AUDIO_INTENSITY=WorldRules.decimal("rbdBodySoundIntensity",()->0.65,0,1);
    public static void initialize(){dev.rbd.phantom.PhantomRules.initialize();WorldRules.initialized=true;}
    private RbdConfig(){}
}
